# Generated by Django 4.2.23 on 2025-08-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0009_alter_consulta_estado_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='estado_respuesta',
            field=models.CharField(blank=True, choices=[('Contestada', 'Contestada'), ('No constestada', 'No constestada'), ('En proceso', 'En proceso')], default='No constestada', max_length=15, null=True),
        ),
    ]
