# Generated by Django 4.2.23 on 2025-11-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0022_alter_consulta_estado_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='estado_respuesta',
            field=models.CharField(blank=True, choices=[('En proceso', 'En proceso'), ('Contestada', 'Contestada'), ('No constestada', 'No constestada')], default='No constestada', max_length=15, null=True),
        ),
    ]
